### ISSUE TITLE
Default widget help text

### ISSUE THREAD

**Issue by cyberjoac** [20tab/django-taggit-live#5]
Hi,
Any chance you could let the default help_text that the Taggit widget proposes?
Something like "A comma-separated list of tags."

Thanks a lot ;-)

**Comment by rafleze** [comment]
Hi @cyberjoac, 
I'm so sorry for my unforgivable late.
Now widget has placeholder as default. But you can modify help_text value using a form like this exemple:
py```
class SomeForm(forms.ModelForm):
    tags = LiveTagField(help_text='A comma-separated list of tags.')

    class Meta:
        model = SomeModel
        exclude = []
```
